#!/bin/bash
#
# This script:
# - installs the back-end CMake scripts
# - compiles the front-end CLI
# - installs it
#

set -e

# Will need to make this up to the user and still work with everything else
HAMMER_INSTALL_DIR="/usr/local/lib/hammer"


if [ -e $HAMMER_INSTALL_DIR ]; then
    $HAMMER_INSTALL_DIR/installers/uninstall.sh
fi

sudo cp -r ./backend     $HAMMER_INSTALL_DIR
sudo cp -r ./installers  $HAMMER_INSTALL_DIR

sudo bash -c "sed 's|@@HAMMER_INSTALL_DIR@@|$HAMMER_INSTALL_DIR|g' $HAMMER_INSTALL_DIR/CMakeLists.txt > $HAMMER_INSTALL_DIR/CMakeLists.txt.tmp"
sudo rm $HAMMER_INSTALL_DIR/CMakeLists.txt
sudo mv $HAMMER_INSTALL_DIR/CMakeLists.txt.tmp $HAMMER_INSTALL_DIR/CMakeLists.txt

# Build and install CLI
cd ./cli
sudo zig build install --prefix /usr/local
cd ..

echo "Done! Run 'hammer help' to get started."

