settings:
# These are the default setting used for compilation, which can be changed 
# when configuring compilation manually.
#
# Run 'hammer config' to do so, or run 'hammer autoconfig' to run with 
# these compilation parameters and no further interaction.
#
# Everything after the 'compilation' mapping is optional and can be omitted.

  - name: here_is_the_binary
    target: project
    type:   executable
    version: 0.1.0
    languages:
      - lang: c
        std: 11

    compilation:
      target-platform: native
      #toolchain: clang
      #profile:   debug-linux
      #build-system: Ninja
      verbose:     false
      strip:       false


