settings:

# These are the default setting used for compilation, which can be changed 
# when configuring compilation manually.
#
# Run 'hammer config' to do so, or run 'hammer autoconfig' to run with 
# these compilation parameters and no further interaction.
#
# Everything after the 'compilation' mapping is optional and can be omitted.
  - name: my_executable
    target: some_project
    type:   executable
    version: 0.1.0
    languages:
      - lang: c
        std: 11
      - lang: c++
        std: 17

      # - lang: zig
      # - lang: asm

    compilation:
      target-platform: native
      toolchain: clang        # how should they specify the toolchain file name?
      profile:   debug        # how should they specify the profile file name?
      build-system: Ninja
      verbose:     false
      strip:       false
      #obfuscate:   false

