#!/bin/bash

gcc -o list_tests linked_list.c -DTESTING -fsanitize=address

gcc -o revsearch reverse_search.c -DBUILDING_EXE -fsanitize=address

gcc -o filecopy_tests filecopy.c -DTESTING -fsanitize=address

